server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feed_news_account?useSSL=false&?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: operaopera
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service-producer # 应用名称
mybatis:
  type-aliases-package: com.opera.micro.producer.model
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5


